title: Engenharia Arquivei
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

authors:
  arquivei:
    name: Engenharia Arquivei
    image: arquivei.png
    about: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec lorem tortor. Sed faucibus egestas felis, ut consequat quam aliquam ut.
    social_networks:
      facebook: facebook
      github: github
      twitter: twitter
      linkedin: linkedin
      email: engenharia@arquivei.com.br
  gustavo_san:
    name: Gustavo Santiago
    job: Frontend Intern
    image: gustavo_san.jpg
    about: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec lorem tortor. Sed faucibus egestas felis, ut consequat quam aliquam ut.
    social_networks:
      github: github
      twitter: twitter
      email: gustavo.santiago@arquivei.com.br
  olinda:
    name: Rafael Mariano
    job: Software Engineer
    image: olinda.jpg
    about: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec lorem tortor. Sed faucibus egestas felis, ut consequat quam aliquam ut.
    social_networks:
      github: toruticas
      twitter: toruticas
      email: rafael.silva@arquivei.com.br


# Disqus
discus-identifier: arquivei # add your discus identifier

# Tracker
analytics: UA-54265512-5 # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "docker-compose.yml"]
